## The Basics 

This notebook will go through the basics working of a neural network by using an example simple neural network in the figure below to illustrate concepts using code. The figure is simple neural network that has 3 layers: a input layer with 3 neurons, a hidden layer with 5 neurons and an output layer with two neurons.

![SimpleNeuralNetwork](https://miro.medium.com/max/1400/0*a_tr0gvjHtW9haUo.png)

Every neuron in each of the layers has a unique connection with the neurons in its adjacent layers. Neurons in a layer will take in values from the previous layer to produce an output for the next. The output is a multiplication of the inputs with the weight of the connection. Each neuron has a unique weight that corresponds to a unique connection and is multiplied with input value of the neuron that is connected.

Below represents how the outer layer will produce its output values by using the input values from the hidden layer in the figure above.

In [24]:
"""
The below code is trying to replicate the output layer of the  neural network 
in the above figure.The inputs, weights and biases are arbituary.
 """
# Initialise the input values. 1 input value for each neuron
inputs = [1.0, 2.0, 3.0, 4.0, 5.0] # There are five neurons in the hidden layer hence there are three input values.
# Initialise the weights for each in the outer layer. 
# Each weight corresponds to a unique connection that the output layer neuron has
weights1 = [0.1, 0.2, 0.3, 0.4, 0.5]
weights2 = [0.11, 0.21,0.31, 0.41, 0.51]
# Initialise the bias values for each output neuron
bias1 = 1
bias2 = 2
"""
The output values for the hidden layer will be multiplication of the values of 
the  neurons in hidden/previous layer. The output will be a list of 2 values
that corresponds to the value of the neuron in that layer
"""
# Calculate the values for the output layer
output = [
inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + \
inputs[3]*weights1[3] + inputs[4]*weights1[4] + bias1,
inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + \
inputs[3]*weights2[3] + inputs[4]*weights2[4] + bias2 
]

# Print out the value of the outer layer
print(output)

[6.5, 7.6499999999999995]


The outer layer produced two values that belongs to each neuron in its layer. A cleaner code is written below.

In [25]:
inputs = [1.0, 2.0, 3.0, 4.0, 5.0]
# Weights is a 2D array of values that belong to each neuron in the outer layer
weights = [[0.1, 0.2, 0.3, 0.4, 0.5],
          [0.11, 0.21,0.31, 0.41, 0.51]]
# Both bias values is now in the same list
biases = [1,2]

# Initialise values for output layer
layer_outputs = []
# Loop through the set of weights and each bias values declared above
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 # Initialise neuron value
# Loop throught inputs declared above and neuron_weights for each neuron
    for n_input, weight in zip(inputs, neuron_weights):
# Increment neuron_output by the multiplication of input and weight
        neuron_output += n_input * weight
# Increment neuron_output by the bias
    neuron_output += neuron_bias
# Append layer_outputs with the final neuron_output value
    layer_outputs.append(neuron_output)

print(layer_outputs)

[6.5, 7.6499999999999995]


The example above multiplies the corresponding inputs and weights to produce an output. In a real neural network, the mutiplication will be dot product.

The inputs variable is 1 dimensional and is a vector. The weights is 2 dimensional and is a matrix. Multiplying both is called the dot product. The code will now look like this below:

In [26]:
# Import numpy to handle arrays
import numpy as np

# Weights comes first as the argument due to shape. You can't multiply a vector with a matrix.
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[6.5  7.65]


In the example, the input layer is a vector representing one sample. To train an neural network multiple samples or vectors is needed. The code below uses a matrix (multiple vectors), as the input layer. To multiply two matrixes, the first matrix must have the same number of columns as the second matrix has rows. If both matrix share the same number of rows, one of the matrix will need to be transposed.

The code below illustrates the input having multiple samples in its matrix. The weight matrix will need to be tranposed so that the matrixes can be transposed.

In [27]:
# Declare inputs ensuring the shape is the same as the weights matrix of the hidden layer neurons
input_layer = [[1.0, 2.0, 3.0, 4.0, 5.0],
               [2.0, -2.0, 3.0, 1.0, 1.0],
               [1.0, -1.0, 5.0, 4.0, 3.0],
               [2.0, 3.0, -3.0, 2.0, -2.0]]
# Declare the weights for hidden layer neurons. Three weights per neuron as there are three unique connections per neuron
hidden_layer_weights = [[0.1,0.2,0.3,0.4,0.5],
                        [0.2,0.1,0.4,-0.2,0.1],
                        [0.1,-0.1,0.2,0.3,0.1],
                        [-0.2,0.4,0.4,-0.2,0.3],
                        [0.1,0.3,0.2,0.4,0.1]]
# Declare the biases for the hidden layer.  
hidden_layer_biases = [2,0.5,1,-2,4]

# Dot product of the transposed inputs matrix and weights matrix 
hidden_layer_output = np.dot(input_layer, np.array(hidden_layer_weights).T) + hidden_layer_biases
print(hidden_layer_output)

[[ 7.5  1.8  3.2  0.5  7.4]
 [ 3.6  1.8  2.4 -1.9  4.7]
 [ 6.5  2.1  3.7 -0.5  6.7]
 [ 1.7 -0.6  0.7 -3.4  5.1]]


The output for the hidden layer above, can then be used as the input for the output layer. 